var _=Object.create;var v=Object.defineProperty;var N=Object.getOwnPropertyDescriptor;var A=Object.getOwnPropertyNames;var U=Object.getPrototypeOf,B=Object.prototype.hasOwnProperty;var u=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var C=(e,t,a,p)=>{if(t&&typeof t=="object"||typeof t=="function")for(let n of A(t))!B.call(e,n)&&n!==a&&v(e,n,{get:()=>t[n],enumerable:!(p=N(t,n))||p.enumerable});return e};var i=(e,t,a)=>(a=e!=null?_(U(e)):{},C(t||!e||!e.__esModule?v(a,"default",{value:e,enumerable:!0}):a,e));var f=u((D,d)=>{d.exports=luna?.core?.modules?.["@luna/core"];if(d.exports===void 0)throw new Error("Cannot find module @luna/core in luna.core.modules");luna.core.LunaPlugin.getByName("@luna/core")?.addDependant(luna.core.LunaPlugin.getByName("Avatar"))});var w=u((E,c)=>{c.exports=luna?.core?.modules?.["@luna/lib"];if(c.exports===void 0)throw new Error("Cannot find module @luna/lib in luna.core.modules");luna.core.LunaPlugin.getByName("@luna/lib")?.addDependant(luna.core.LunaPlugin.getByName("Avatar"))});var y=u((k,m)=>{m.exports=luna?.core?.modules?.["@luna/ui"];if(m.exports===void 0)throw new Error("Cannot find module @luna/ui in luna.core.modules");luna.core.LunaPlugin.getByName("@luna/ui")?.addDependant(luna.core.LunaPlugin.getByName("Avatar"))});var x=u((T,g)=>{g.exports=luna?.core?.modules?.react;if(g.exports===void 0)throw new Error("Cannot find module react in luna.core.modules");luna.core.LunaPlugin.getByName("react")?.addDependant(luna.core.LunaPlugin.getByName("Avatar"))});var b=i(f()),r=i(w()),s=i(y()),l=i(x());var h=await __ipcRenderer.invoke("__Luna.registerNative","Avatar/md5.native.ts",`"use strict";var i=Object.defineProperty;var a=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var n=Object.prototype.hasOwnProperty;var c=(t,e)=>{for(var s in e)i(t,s,{get:e[s],enumerable:!0})},g=(t,e,s,m)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of d(e))!n.call(t,r)&&r!==s&&i(t,r,{get:()=>e[r],enumerable:!(m=a(e,r))||m.enumerable});return t};var p=t=>g(i({},"__esModule",{value:!0}),t);var x={};c(x,{md5:()=>h});module.exports=p(x);var o=require("crypto"),h=async t=>(0,o.createHash)("md5").update(t).digest("hex");0&&(module.exports={md5});
`);if(h===void 0)throw new Error("Failed to register native module Avatar/md5.native.ts");var P=(...e)=>__ipcRenderer.invoke(h,"md5",...e);var L=new Set,O=new r.StyleTag("avatarCSS",L),o=await b.ReactiveStore.getPluginStorage("Avatar"),S=async e=>{if(e===""||e===void 0){let t=await P(r.redux.store.getState().user.meta.email);return o.customUrl=`https://www.gravatar.com/avatar/${t}?d=identicon`}O.css=`
		[class^="_profilePicture_"] {
			background-image: url("${e}");
			background-size: cover;
		}

		[class^="_profilePicture_"] svg {
			display: none;
		}
	`};(0,r.safeTimeout)(L,()=>{S(o.customUrl)},250);var q=()=>{let[e,t]=l.default.useState(o.customUrl);return l.default.createElement(s.LunaSettings,null,l.default.createElement(s.LunaTextSetting,{title:"Avatar url",desc:"Url to the avatar image you want to use. If empty Gravatar will be used.",value:e,onChange:async a=>{o.customUrl=a.target.value,t(await S(o.customUrl))}}))};export{q as Settings,o as settings,L as unloads};
//# sourceMappingURL=Avatar.mjs.map
